CATEGORY_AMERICAS = "Americas"
CATEGORY_EUROPE = "Europe"
CATEGORY_ASIA = "Asia"
CATEGORYS = (CATEGORY_AMERICAS, CATEGORY_EUROPE, CATEGORY_ASIA)

SUBSCRIBE_STATUS_ON = "on"
SUBSCRIBE_STATUS_OFF = "off"

LOCALES = ("en", "zh_CN", "zh_TW")
